# Generated by Django 4.2.5 on 2023-09-17 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project2', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PeopleYouMayKnow',
            fields=[
                ('name', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=255)),
                ('mutual_connections', models.PositiveIntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project2.user')),
            ],
        ),
        migrations.CreateModel(
            name='PeopleAlsoViewed',
            fields=[
                ('name', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('college', models.CharField(max_length=255)),
                ('connections', models.PositiveIntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project2.user')),
            ],
        ),
        migrations.CreateModel(
            name='Interests',
            fields=[
                ('name', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('followers', models.CharField(max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project2.user')),
            ],
        ),
    ]
