# Generated by Django 3.2.21 on 2023-09-26 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project2', '0004_alter_education_user_alter_interests_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interests',
            name='name',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='peoplealsoviewed',
            name='name',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='peopleyoumayknow',
            name='name',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='resources',
            name='name',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='skills',
            name='skill_name',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
    ]
